# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 891099a86be8c7c2fd6757eba484445c2ea6c2fbb9db02992e88387d1fb661bad888721f49008ea41900f035b4021765ad0313dfd5d0a15e8ef3cfff8e02d706

test:
  secret_key_base: 0c1d13fd87e3418d7bba1b43b01f51e8fd96656db68a4c7c9d27dc3ce25e980fcf07613069f2d1112883d2bbf14ac9faaea8295c3047b2cd1b495e1a63f92b17

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
